before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
#      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    main: ./cmd/anchor/main.go

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
      files:
        - README.md
        - LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: "{{ .ProjectName }}"
    tap:
      owner: ZachiNachshon
      name: homebrew-tap
    folder: Formula
    description: Dynamic versioned controlled remote marketplace for local / CI environments
    license: MIT
    test: |
      system "#{bin}/{{ .ProjectName }} --version"
    dependencies:
      - name: go
        type: optional
      - name: git
    install: |
      bin.install "{{ .ProjectName }}"