name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build / Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18' ]

    steps:
      - name: Set up Go env
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Set up tparse formatter
        run: go install github.com/mfridman/tparse@v0.10.0

      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Build
        run: |
          ls -lah
          ls -lah ./external
          ls -lah /home/runner/work/anchor/anchor/external/shell-scripts-lib/golang
          make build-to-gobin-ci

      - name: Run tests
        run: make test-github-ci

      - name: Coverage
        uses: jandelgado/gcov2lcov-action@v1.0.6

      - name: Coverage Reporter
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov


