name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  TPARSE_VERSION: "v0.10.0"

jobs:
  build:
    name: Build / Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20' ]

    steps:
      - name: Set up Go env
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Try Load Cache - tparse
        id: cached-go-package-tparse
        uses: actions/cache@v3
        with:
          path: $GOBIN/tparse
          key: tparse-${{ env.TPARSE_VERSION }}

      - name: Maybe Install - tparse
        if: steps.cached-go-package-tparse.outputs.cache-hit != 'true'
        run: |
          go install github.com/mfridman/tparse@${{ env.TPARSE_VERSION }}
          
      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Install to GOBIN
        run: make install

      - name: Run tests
        run: make test-with-coverage

      - name: Coverage
        uses: jandelgado/gcov2lcov-action@v1.0.6

      - name: Coverage Reporter
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov


