name: CI

on:
  push:
    branches:
      - master
      - pivot
  pull_request:
    branches:
      - master
      - pivot

jobs:
  build:
    name: Build / Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16' ]

    steps:
      - name: Set up Go env
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Run tests
        run: make run-tests-ci


